laravelアプリ開発
ayano-kobayashi-lvgs/laravel_todo_default pull request #1
Opened 2022-07-28 00:59 UTC by ayano-kobayashi-lvgs

2022-07-28 02:16 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
コメントしました！

2022-07-28 02:16 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $todo->save();
更新処理なので、Modelで関数定義してほしい！

2022-07-28 02:16 UTC, takuya-nakamatsu-lvgs commented on src/app/Models/Todo.php
> +    use HasFactory;
使ってないから削除してほしい

2022-07-28 02:16 UTC, takuya-nakamatsu-lvgs commented on src/resources/views/todo/index.blade.php
> +                            <th></th>
これって使ってる？

2022-07-28 02:16 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $todo->save();
保存処理なので、Modelで関数定義してほしい！

2022-07-28 02:16 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $todo->delete();
ココもModelで定義かな！

2022-07-28 02:16 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/TodoController.php
> +
改行削除

2022-07-29 02:54 UTC, takulev reviewed
@ayano-kobayashi-lvgs
レビューしました！

2022-07-29 02:54 UTC, takulev commented on src/app/Http/Controllers/TodoController.php
> +     */
```suggestion
     */
```

2022-07-29 02:54 UTC, takulev commented on src/app/Http/Controllers/TodoController.php
> +     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
細かいけど笑
```suggestion
     * @return RedirectResponse
```

2022-07-29 02:54 UTC, takulev commented on src/app/Models/Todo.php
> +    public function create(array $values)
ここも返り値の型してほしい！

2022-07-29 02:54 UTC, takulev commented on src/app/Models/Todo.php
> +    public function updateTodo(int $id, array $values)
>ここも返り値の型してほしい！

ここも

2022-07-29 10:30 UTC, jaegon-kim-lvgs requested changes

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/routes/console.php
> +})->purpose('Display an inspiring quote');
必要なければ削除

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/routes/channels.php
> +});
必要なければ削除

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/routes/api.php
> +});
必要なければ削除

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/resources/views/welcome.blade.php
> +<!DOCTYPE html>
必要なければ削除

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/routes/web.php
> +Route::get('todos/create', 'TodoController@create');
特にgetにはroutenameをつけて、リンク生成などに使ってください

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/resources/views/todo/show.blade.php
> +                    href="{{ url('todos') }}">
URL定義をrouteに集約するためにurlの代わりにrouteヘルパーを使ってください。

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/resources/views/layouts/app.blade.php
> +<html lang="{{ str_replace('_', '_', app()->getLocale())}}">
`str_replace('_', '-',`なのでは？

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/public/.htaccess
> +<IfModule mod_rewrite.c>
必要ないので、削除（apache用ファイルです）

2022-07-29 10:30 UTC, jaegon-kim-lvgs commented on src/database/migrations/2019_08_19_000000_create_failed_jobs_table.php
> +        Schema::create('failed_jobs', function (Blueprint $table) {
queueを導入するのであれば、jobsもあるはずですがないです。

2022-08-02 01:38 UTC, jaegon-kim-lvgs commented on src/app/Http/Controllers/TodoController.php
> +     * @return RedirectResponse
（要議論）定義している内容（param, returnなど）は特にコメントしなくていいと思う

2022-08-02 02:00 UTC, takulev approved these changes
LGTM

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on docker-compose.yml
> +      MYSQL_DATABASE: laravel
【作成】

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on Dockerfile
> +COPY --from=composer:1.10.12 /usr/bin/composer /usr/bin/composer
【変更】

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +}
【作成】TodoController

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Models/Todo.php
> +}
【作成】Todo

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Providers/RouteServiceProvider.php
> +    protected $namespace = 'App\Http\Controllers';
【追加】

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/database/migrations/2022_07_26_001041_create_todos_table.php
> +}
【作成】create_todos_table

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/routes/web.php
> +Route::delete('todos/{id}', 'TodoController@destroy');
【追加】ルート

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/resources/views/layouts/app.blade.php
> +</html>
【作成】app.blade.php

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/resources/views/todo/create.blade.php
> +@endsection
【作成】create.blade.php

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/resources/views/todo/index.blade.php
> +                            <th></th>
使ってます！

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $todo->save();
対応済みです

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Models/Todo.php
> +    use HasFactory;
対応済みです

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $todo->save();
対応済みです

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $todo->delete();
対応済みです

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +
対応済みです

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +}
【修正箇所】

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Models/Todo.php
> +}
【修正箇所】

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/database/migrations/2022_07_26_001041_create_todos_table.php
> +}
【修正箇所】

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/database/migrations/2019_08_19_000000_create_failed_jobs_table.php
> +        Schema::create('failed_jobs', function (Blueprint $table) {
削除しました。

2022-08-02 02:17 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +     * @return RedirectResponse
@jaegon-kim-lvgs
ありがとうございます。
個人的な意見なのですが、、、コメントあったほうがいいかなと思い、追加しました。

理由は下記のとおりです。
1. 記入すると、VSCode上で関数の引数や戻り値などを参照できるから。（下図参考）
![スクリーンショット 2022-08-02 11 09 26](https://user-images.githubusercontent.com/109648661/182276579-ac2e855f-6c5d-453a-886e-78e1ab958e31.png)
2. 共通認識を持つことができるから。（初心者にとって優しい）
3. ライブラリも記述されているから。

2022-08-03 03:08 UTC, merged