ユーザ登録(1)
ayano-kobayashi-lvgs/laravel_todo_default pull request #2
Opened 2022-08-03 01:26 UTC by ayano-kobayashi-lvgs

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/UserRequest.php
> +            'password_confirmation' => 'regex:/^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,24}$/',
フィールド名に対するバリデーションルールの定義方法は配列の方がいいかな。

理由）カスタムルールを定義する必要が発生した場合に、文字列から配列に変更することになってしまう

▼ 例：「Uppercase」というカスタムルールの場合 ▼
```php
$request->validate([
    'name' => ['required', 'string', new Uppercase],
]);
```
※参考：https://readouble.com/laravel/9.x/ja/validation.html?#custom-validation-rules

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/UserRequest.php
> +    public function authorize()
FormReqeustの`authorize()`, `messages()`は、今後他のFormRequestを作成した場合にも共通して使用する関数だと思うので、親クラスにまとめて、これらを継承する感じで設計しても良いかも！

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/app/Models/User.php
> +        ];
この書き方にすると、他のコントローラーで追加のカラムの値を保存したい場合に書き直す必要があるから、
カラムの指定は呼び出し元で定義できるように書いた方がいい

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/css/style.css.map
> +{"version":3,"sources":["style.css","../scss/foundation/_variable.scss","../scss/foundation/_base.scss","../scss/foundation/_reset.scss","../scss/object/component/_button.scss","../scss/object/compon
これってVscodeの拡張機能の「Live Sass Compiler」で自動生成されるファイルだよね？
sassはwebpackでコンパイルしてるはずだから、必要ないかな

もし今、Live Sass Compilerでコンパイルしているなら、webpackを使用したコンパイルで開発してほしい！

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/foundation/_reset.scss
> +  letter-spacing: 1.5;
インデントずれ！

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/foundation/_variable.scss
> +// white
カラーのコメント必要ない気がしたり笑
変数名見たら何色か誰でも分かるとおもう

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/object/component/_section.scss
> +// c-section
```suggestion

```

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/object/component/_button.scss
> +    // width: 10em;
```suggestion

```

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/object/component/_section.scss
> +
```suggestion
```

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/object/component/_section.scss
> +        &Item {
キャメルケースの途中で`&`はしない方が良い気がする笑
そんな長い単語でもないし笑

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/scss/object/project/_user-register.scss
> +@use "../../foundation/variable" as *;
このファイル使ってる？

2022-08-03 06:13 UTC, takuya-nakamatsu-lvgs commented on src/resources/setting.json
> +{
これもlive sass conpilerの設定ファイルだよね？？
もしそうだったら必要ないかな

2022-08-03 06:13 UTC, takulev commented on src/resources/views/auth/user-register.blade.php
> +                        {{csrf_field()}}
```suggestion
                        {{ csrf_field() }}
```

2022-08-03 06:13 UTC, takulev commented on src/resources/views/auth/user-register.blade.php
> +                                    >
```suggestion
                                    name="password">
```

2022-08-03 06:13 UTC, takulev commented on src/resources/views/auth/user-register.blade.php
> +                                    >
```suggestion
                                    name="password_confirmation">
```

2022-08-03 06:13 UTC, takulev commented on src/app/Http/Requests/UserRequest.php
> +<?php
このファイル（コントローラー）についてのコメントではないんだけど、
本当なら登録処理のルーティングもこのPRに含めた方が良いかな！

今回は認識だけもってもらえると！

2022-08-03 06:13 UTC, takulev commented on src/app/Http/Controllers/Auth/UserController.php
> +    public function completeRegister(UserRequest $request): View
`register()`と`completeRegister(`がMECEじゃないのが少し気になる。笑
`showRegister()`, `executeRegister()`とかは？他にいい案あればそれでも！

2022-08-03 06:13 UTC, takulev commented on src/app/Http/Controllers/Auth/UserController.php
> +        return view('auth.user-register-result');
>user-register-result

どちらかというと`resulet`（結果）より`complete`（完了）の方が適切な気もしたり

2022-08-03 06:14 UTC, takulev commented on src/app/Http/Controllers/Auth/UserController.php
> +        $this->user->create($values);
`$values`定義しなくても良いかな！
変数定義するケースは下記の場合くらいな気がする。
- 二箇所以上で定義する時
- 変数のデータが別のインスタンスに変わる時
   - ex) `$post = $user->post` のようなuserインスタンスからpostのインスタンスへ変わる場合は、データ型が変わったことを読み手に伝えることで、可読性向上を図るため
- 複雑なソースコードをシンプルにしたい時

```suggestion
        $this->user->create($request->validated());
```

2022-08-03 06:20 UTC, takulev commented
@ayano-kobayashi-lvgs 
コメントしました！

2022-08-03 11:43 UTC, jaegon-kim-lvgs requested changes

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/public/mix-manifest.json
> +{
mix-manifestはgitから除外してください。（compileによる生成ファイル）

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/webpack.mix.js
> +    .postCss('resources/css/style.css', 'public/css', [
必要なさそうですが、削除していいのでは？（ファイルも）

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/webpack.mix.js
> +mix.sass('resources/scss/style.scss', 'public/css');
public下のcompileによる生成ファイルはgitから除外してください。

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/resources/scss/foundation/_variable.scss
> +$font-xxs: 10x;
10x -> 10px

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/resources/views/auth/user-register-result.blade.php
> +    <link rel="stylesheet" href="/css/style.css">
パス指定にasset()を使ってください

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/resources/views/auth/user-register-result.blade.php
> +  </body>
indentをそろえてください。

2022-08-03 11:43 UTC, jaegon-kim-lvgs commented on src/resources/views/auth/user-register.blade.php
> +<!DOCTYPE html>
レイアウトやコンポーネントなどを使って共通化してください
https://readouble.com/laravel/9.x/ja/blade.html

2022-08-04 07:30 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register-result.blade.php
> +                        </button>
こちらの遷移先指定は、次のフェーズ（認証）で実装します。

2022-08-04 07:30 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/UserRequest.php
> +        ];
ここは、もっとシンプルにさせたいと思っています。
もう少し時間があれば、調査したかった点です。

2022-08-04 07:30 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/object/project/_user-register.scss
> +// register
ログイン画面と差分をつける用（今後使用予定）
不要だったら削除予定。

2022-08-04 07:30 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/UserRequest.php
> +    public function authorize()
後で要確認

2022-08-04 07:30 UTC, ayano-kobayashi-lvgs commented on src/app/Models/User.php
> +        ];
後で要確認

2022-08-04 07:30 UTC, ayano-kobayashi-lvgs commented on src/resources/css/style.css.map
> +{"version":3,"sources":["style.css","../scss/foundation/_variable.scss","../scss/foundation/_base.scss","../scss/foundation/_reset.scss","../scss/object/component/_button.scss","../scss/object/compon
後で要確認

2022-08-04 23:43 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/UserRequest.php
> +            'password_confirmation' => 'regex:/^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,24}$/',
修正済み

2022-08-04 23:44 UTC, ayano-kobayashi-lvgs commented on src/resources/css/style.css.map
> +{"version":3,"sources":["style.css","../scss/foundation/_variable.scss","../scss/foundation/_base.scss","../scss/foundation/_reset.scss","../scss/object/component/_button.scss","../scss/object/compon
修正済み

2022-08-04 23:45 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/foundation/_reset.scss
> +  letter-spacing: 1.5;
修正済み

2022-08-04 23:45 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register.blade.php
> +                                    >
修正済み

2022-08-04 23:45 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register.blade.php
> +                                    >
修正済み

2022-08-04 23:46 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/UserRequest.php
> +<?php
すみません、漏れていました・・

2022-08-04 23:48 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/UserController.php
> +    public function completeRegister(UserRequest $request): View
修正済み

2022-08-04 23:48 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/UserController.php
> +        $this->user->create($values);
修正済み

2022-08-04 23:49 UTC, ayano-kobayashi-lvgs commented on src/webpack.mix.js
> +    .postCss('resources/css/style.css', 'public/css', [
修正済み

2022-08-04 23:49 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/foundation/_variable.scss
> +$font-xxs: 10x;
修正済み

2022-08-04 23:49 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register-result.blade.php
> +    <link rel="stylesheet" href="/css/style.css">
修正済み

2022-08-04 23:50 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register-result.blade.php
> +  </body>
修正済み

2022-08-04 23:58 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/UserController.php
> +        return view('auth.user-register-result');
修正済み

2022-08-04 23:58 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/object/component/_section.scss
> +// c-section
修正済み

2022-08-04 23:58 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/object/component/_section.scss
> +
修正済み

2022-08-04 23:58 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/object/component/_section.scss
> +        &Item {
修正済み

2022-08-04 23:58 UTC, ayano-kobayashi-lvgs commented on src/resources/scss/object/project/_user-register.scss
> +@use "../../foundation/variable" as *;
後ほど使用します

2022-08-04 23:58 UTC, ayano-kobayashi-lvgs commented on src/resources/setting.json
> +{
はい！

2022-08-04 23:59 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register.blade.php
> +                        {{csrf_field()}}
version 5.6以降は”@csrf”と記述するそうなので、@csrfに変更しました。

2022-08-05 01:54 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/user-register.blade.php
> +<!DOCTYPE html>
修正済み

2022-08-05 03:33 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/UserRequest.php
> +    public function authorize()
修正済み

2022-08-05 07:36 UTC, ayano-kobayashi-lvgs commented on src/app/Models/User.php
> +        ];
修正済み

2022-08-08 00:45 UTC, takulev reviewed
コメントしました！

2022-08-08 00:45 UTC, takulev commented on src/app/Http/Controllers/Auth/UserController.php
> +        $this->user->create($values->only(['name', 'email', 'password',]));
書き直さなくてもいいけど、パフォーマンス的にはこっちの方が良いかな！
（自分がこの書き方を教えたから書いてくれていると思うけど）

```suggestion
        $this->user->create([
              'name' => $request->name,
              'email' => $request->email,
              'password' => Hash::make($request->password)
        ]);
```

2022-08-08 00:45 UTC, takulev commented on src/app/Http/Controllers/Auth/UserController.php
> +        $this->user->create($values->only(['name', 'email', 'password',]));
▼ `merge()`の詳細 ▼
https://github.com/laravel/framework/blob/6c83a59c1c5e8a91d37c5e7501ea75ad28f5e13d/src/Illuminate/Http/Request.php#L342-L353

▼ `only()`の詳細 ▼
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Http/Concerns/InteractsWithInput.php#L376-L399

2022-08-08 00:45 UTC, takulev commented on src/app/Http/Requests/BaseRequest.php
> +
```suggestion
```

2022-08-08 00:45 UTC, takulev commented on src/resources/views/todo/create.blade.php
> +                                >
```suggestion
                                type="text">
```

2022-08-08 00:45 UTC, takulev commented on src/resources/views/auth/user-register.blade.php
> +                        method="post">
細かいけど、大文字で定義してるファイルと小文字で定義されているファイルが混在しているね笑
他は大文字しているみたいだから、ここも大文字で良いんじゃない？

2022-08-08 00:45 UTC, takulev commented on src/resources/views/todo/index.blade.php
> +                                        href="{{ route('todos.delete', ['id' => $todo->id]) }}">
href必要ない気がする（たぶん）

2022-08-08 00:45 UTC, takulev commented on src/resources/views/todo/index.blade.php
> +                                        <button class="btn btn-danger">削除</button>
細かい仕様忘れちゃったけど、
typeプロパティにsubmitを定義しなくてもいいんだっけ？

2022-08-08 00:45 UTC, takulev commented on src/routes/web.php
> +Route::post('auth/register', [UserController::class, 'executeRegister'])->name('auth.completeRegister');
Routeのgroupに入れて良さそう！
あと、`name()`が修正されてないかな

2022-08-08 00:45 UTC, takulev commented on src/app/Http/Requests/UserRequest.php
> +        ], BaseRequest::BASE_RULES);
これで良い気がしたんだけどどうだろう？
具体的なクラス名が指定されていると、他のクラスから引っ張ってきた印象を少し感じる。
（好みの問題な気がするから修正するか任せますw）

```suggestion
        ], self::BASE_RULES);
```

2022-08-08 00:45 UTC, takulev commented on src/resources/views/todo/show.blade.php
> +                            <td>{{$todo->id}}</td>
他のファイルはこの書き方してるっぽい
```suggestion
                            <td>{{ $todo->id }}</td>
```

2022-08-08 00:45 UTC, takulev commented on src/resources/views/todo/show.blade.php
> +                            <td>{{$todo->title}}</td>
ここも！
```suggestion
                            <td>{{ $todo->title }}</td>
```

2022-08-08 01:38 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
https://www.lgtmgifs.com/gifs/spongebob-many-thumbs

2022-08-08 01:38 UTC, takulev approved these changes

2022-08-09 04:22 UTC, jaegon-kim-lvgs requested changes

2022-08-09 04:22 UTC, jaegon-kim-lvgs commented on src/public/index.php
> -<?php
publicのfavicon.ico, index.php, robots.txtは必須なので、削除しないでください。

2022-08-09 08:13 UTC, merged