Feature/authentication
ayano-kobayashi-lvgs/laravel_todo_default pull request #3
Opened 2022-08-04 05:33 UTC by ayano-kobayashi-lvgs

2022-08-04 07:04 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
コメントしました！

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/Auth/LoginController.php
> +        if (Auth::attempt($cledentials)) {
これでいいかな！
```suggestion
        if (Auth::attempt($request->validated())) {
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/Auth/LogoutController.php
> +        $request->session()->regenerateToken();
これって必要なのー？

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/Auth/LogoutController.php
> +        $request->session()->regenerateToken();
>$request->session()->invalidate();

この処理の中に含まれていそう
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Session/Store.php#L485-L490

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Middleware/Authenticate.php
> +     *
細かいけど笑
```suggestion
     *
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/AuthRequest.php
> +class AuthRequest extends FormRequest
このコメントと同じ
https://github.com/ayano-kobayashi-lvgs/laravel_todo_default/pull/2#discussion_r936252302

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Providers/ComposeServiceProvider.php
> +            }
個人的には、こっちのほうが拡張性あるから（複数の値を指定できるから）好き笑
```suggestion
            if(auth()->check()) {
                $name = auth()->user()->name;
                $view->with(compact('name'));
            }
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Providers/ComposeServiceProvider.php
> +class ComposeServiceProvider extends ServiceProvider
viewcomposerを使ってみてるのは良いね！

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/resources/views/auth/login.blade.php
> +    <link rel="icon" href="{{ asset('/img/gopher.gif') }}" type="image/gif" >
```suggestion
    <link rel="icon" href="{{ asset('/img/gopher.gif') }}" type="image/gif">
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/AuthRequest.php
> +            'email'=>'required|email',
bladeでは文字数制限しているのに、バリデーション側で文字数制限のルールがない！

```blade
                                <input
                                    class="c-form__inner"
                                    type="email"
                                    name="email"
                                    maxlength="254"
                                    required>
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/AuthRequest.php
> +            'email'=>'required|email',
今回はここまでしなくても良いけど、メールアドレスのバリデーションルールは奥深いことだけ認識してもらえると！

https://qiita.com/zako1560/items/a463fab7b698e09eb5a0

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/resources/views/layouts/app.blade.php
> +            @endif
ビューコンポーザーで認証判定しているなら、変数の存在チェックだけでいいんじゃない？
もし`\Auth::check()`使用するなら、viewファイル内で`\Auth`からユーザー名取得してもいい気がする！

```suggestion
        <div class="c-menu__itemWrap">
             @if(isset($name))
                <p class="c-menu__text">こんにちは、{{ $name }}さん</p>
            @endif
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/Auth/LoginController.php
> +    public function getLoginPage()
`get`は「取得する」という意味になるから、ページ表示を意味する関数名には不適切かな。
仮に`view()`の引数に設定するページ名の値を取得する関数の命名にするとかならまだ理解できる。

`index()`とかで良いじゃない？
参考：https://readouble.com/laravel/8.x/ja/controllers.html#actions-handled-by-resource-controller

ちなみに、前のチームは入力フォームのページ表示の関数名は`input()`で統一してた。
（チームの運用によると思うけども笑）

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/Auth/LoginController.php
> +    public function authenticateUser(AuthRequest $request)
ここも`login()`だけで良い気がする笑

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/Auth/LoginController.php
> +        ]);
ユーザー登録のPRでコメントし損ねたけど、「メールアドレスまたはパスワードが一致しません。」という文字は、本来はview側で担保すべきかな！
（修正するかは任せます笑）

個人的には下記のようにbooleanのフラグだけviewへ渡して、そのbooleanをviewで判定してエラーテキストを表示する方がすき笑


```suggestion
        return redirect()->route('auth.login')->with('isLoginError', true);
```

2022-08-04 07:04 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/AuthRequest.php
> +            'password' => 'required',
あと、データ型チェックと文字数制限が必要かな。

2022-08-04 07:04 UTC, takulev commented on src/app/Http/Controllers/Auth/LoginController.php
> +        if (Auth::attempt($cledentials)) {
ログインできない状態が異常系なので、ログインできなかった場合をif文にすべき！

2022-08-04 07:04 UTC, takulev commented on src/routes/web.php
> +Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
getリクエスト以外はgroupの中に含めないのー？

2022-08-04 07:28 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/LoginController.php
> +<?php
ユーザ登録でもご指摘いただいた点は次回のレビュー修正に反映します。
・ビュー：HTML上でのCSSの指定やコンポネントの利用など
・バリデーション：ルールの記述方法など

2022-08-04 08:51 UTC, jaegon-kim-lvgs requested changes

2022-08-04 08:51 UTC, jaegon-kim-lvgs commented on src/resources/views/layouts/app.blade.php
> +            @endif
補足ですが、Blade内では@authを使った方がいいです
https://readouble.com/laravel/9.x/ja/blade.html

2022-08-04 08:51 UTC, jaegon-kim-lvgs commented on src/resources/views/auth/login.blade.php
> +        <div class="c-section__inner">
全体的にインデントをそろえてください

2022-08-04 08:51 UTC, jaegon-kim-lvgs commented on src/resources/views/auth/login.blade.php
> +
1行空いている

2022-08-04 08:51 UTC, jaegon-kim-lvgs commented on src/app/Http/Middleware/Authenticate.php
> +            return route('auth.login');
ログインページへのリダイレクトなので、route('login')が正しいと思います。

2022-08-04 08:51 UTC, jaegon-kim-lvgs commented on src/app/Http/Controllers/Auth/LogoutController.php
> +        $request->session()->regenerateToken();
> > $request->session()->invalidate();
> 
> この処理の中に含まれていそう https://github.com/laravel/framework/blob/8.x/src/Illuminate/Session/Store.php#L485-L490

regenerateTokenはCSRFトークンの再生成なのでinvalidateに入ってないはず

2022-08-05 08:28 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/LoginController.php
> +        if (Auth::attempt($cledentials)) {
修正済み

2022-08-05 10:19 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Middleware/Authenticate.php
> +            return route('auth.login');
auth.loginにリダイレクトするように設定しましたが、あまりよろしくないでしょうか？

2022-08-08 01:08 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
コメントしました！概ね問題ないと思います！

2022-08-08 01:08 UTC, takulev commented on src/app/Http/Controllers/Auth/LoginController.php
> +        if (!(Auth::attempt($request->validated()))) {
```suggestion
        if (!Auth::attempt($request->validated())) {
```

2022-08-08 01:08 UTC, takulev commented on src/resources/views/auth/login.blade.php
> +                            action="{{route('auth.login')}}"
```suggestion
                            action="{{ route('auth.login') }}"
```

2022-08-08 01:08 UTC, takulev commented on src/resources/views/todo/index.blade.php
> +                @if (session('status'))
```suggestion
                @if(session('status'))
```

2022-08-08 01:36 UTC, takulev approved these changes
@ayano-kobayashi-lvgs 
![Curry Dance](https://media.giphy.com/media/AJMPKDi4jV4me4FZ74/giphy.gif)

2022-08-09 08:17 UTC, merged