認可
ayano-kobayashi-lvgs/laravel_todo_default pull request #4
Opened 2022-08-09 09:35 UTC by ayano-kobayashi-lvgs

2022-08-09 09:42 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
自動保存したら改行されました

2022-08-09 09:42 UTC, ayano-kobayashi-lvgs commented on src/app/Policies/TodoPolicy.php
> +{
コメントご確認ください

2022-08-09 09:42 UTC, ayano-kobayashi-lvgs commented on src/app/Providers/AppServiceProvider.php
> +
コメントご確認ください

2022-08-09 09:42 UTC, ayano-kobayashi-lvgs commented on src/resources/views/errors/403.blade.php
> +{{--このファイルだけ使用しています。他のエラー関連ファイルは残しておいて大丈夫ですか？--}}
コメントご確認ください

2022-08-09 09:42 UTC, ayano-kobayashi-lvgs commented on src/routes/web.php
> +    Route::delete('/{id}', [TodoController::class, 'delete'])->whereNumber('id')->can('delete', Todo::class)->name('delete');
◆アクション制御（CRUD操作）
ポリシー定義して、ミドルウェア経由で権限でcanメソッドを呼んでいます。
（理由：ファイル1つでまとめて制御できて、漏れが発生しにくいため）

2022-08-09 09:44 UTC, ayano-kobayashi-lvgs commented on src/routes/web.php
> +    Route::get('/{id}/edit', [TodoController::class, 'edit'])->whereNumber('id')->name('edit');
◆URL直接アクセス制御（対象GETメソッド）
ゲート定義して、ミドルウェア経由で権限有無を判断しています。

2022-08-09 09:46 UTC, ayano-kobayashi-lvgs commented on src/app/Providers/AppServiceProvider.php
> +        });
ゲート定義
bladeでのボタン表示・非表示もこちらを利用しています。

2022-08-10 00:29 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
コメントしました！

2022-08-10 00:29 UTC, takuya-nakamatsu-lvgs commented on src/app/Policies/TodoPolicy.php
> +{
>自動生成されたものは削除したほうが良いですか？

そうだね！

2022-08-10 00:29 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/TodoController.php
> +    public function delete(Request $request, int $id, Todo $todo): RedirectResponse
ここも

```suggestion
    public function delete(Request $request, int $id): RedirectResponse
```

2022-08-10 00:29 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Controllers/TodoController.php
> +    public function update(Request $request, int $id, Todo $todo): RedirectResponse
>Todo $todo

使ってない...？


```suggestion
    public function update(Request $request, int $id): RedirectResponse
```

2022-08-10 00:29 UTC, takuya-nakamatsu-lvgs commented on src/app/Policies/TodoPolicy.php
> +        return $user->role === 'admin';
文字列`admin`は、テーブルのカラムに沿ってEnum作成して管理しても良いかもね！

▼ 参考 ▼
https://qiita.com/KuruwiC/items/759bc981aa893029c5c6

2022-08-10 00:29 UTC, takuya-nakamatsu-lvgs commented on src/app/Providers/AppServiceProvider.php
> +
>こちらも不要であれば削除したほうが良いですか？

プロバイダーはポリシーと違って、アプリケーション全体を管理するファイルで追加の仕様で`register()`を使う可能性が高いので、削除しなくて大丈夫！

2022-08-10 00:29 UTC, takuya-nakamatsu-lvgs commented on src/resources/views/errors/403.blade.php
> +{{--このファイルだけ使用しています。他のエラー関連ファイルは残しておいて大丈夫ですか？--}}
>コメントご確認ください

次回から、ソースコードのコメントではなくgithubのコメント機能使ってねｗ



**【理由】**
下記が発生する可能性がある
- レビュアーの確認漏れ
- レビュー後に実装者のコメントの削除漏れ

2022-08-10 00:29 UTC, takulev commented on src/resources/views/errors/403.blade.php
> +{{--このファイルだけ使用しています。他のエラー関連ファイルは残しておいて大丈夫ですか？--}}
>このファイルだけ使用しています。他のエラー関連ファイルは残しておいて大丈夫ですか？

下記のあたり考えてみて！
- 403以外のステータスコードが発生する可能性はあるのか
- ステータス番号別のエラーページ表示のロジックをどこで、どのように実現しているか
   - カスタマイズしたい場合はどのようにすべきか
- 上記を鑑みて、必要ないと判断したエラーファイルを削除しても、対応できるためにどうしたらよいか

2022-08-10 00:29 UTC, takulev commented on src/resources/views/errors/403.blade.php
> +@section('title', __('アクセスエラー'))
これ必要？
というのと、`__()`の関数は調べて理解した上で使ってね！

2022-08-10 00:29 UTC, takulev commented on src/routes/web.php
> +    Route::get('/{id}/edit', [TodoController::class, 'edit'])->whereNumber('id')->name('edit');
29行目のルートグループと別で、37行目のルートグループを新しく定義している理由ありそう？

2022-08-10 00:30 UTC, takulev commented
@ayano-kobayashi-lvgs 

あ、ごめん
これって、昨日言ってたレビューを取り消すって言ってたやつかｗ

2022-08-10 02:38 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +    public function update(Request $request, int $id, Todo $todo): RedirectResponse
ポリシー関連で引数に追加しましたが、不要です。削除漏れです・・。

2022-08-10 02:38 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +    public function delete(Request $request, int $id, Todo $todo): RedirectResponse
ポリシー関連で引数に追加しましたが、不要です。削除漏れです・・。

2022-08-10 02:38 UTC, ayano-kobayashi-lvgs commented on src/app/Policies/TodoPolicy.php
> +        return $user->role === 'admin';
それユーザ登録のbladeでもやりたいとおもっていました！

2022-08-10 02:38 UTC, ayano-kobayashi-lvgs commented on src/resources/views/errors/403.blade.php
> +                            {{--<a href="{{ url()->previous() }}">戻る</a>--}}
もとにいたページに戻るようにするか一覧に戻るか迷っています

2022-08-10 02:38 UTC, ayano-kobayashi-lvgs commented on src/routes/web.php
> +    Route::get('/{id}/edit', [TodoController::class, 'edit'])->whereNumber('id')->name('edit');
上記2つの説明のとおりです。
前者はadmin, userともにアクセスできるようになっています。
後者はadmin以外アクセスできないようにしています。

> 'can:isAdmin'

違いはこの記述の有無です。

2022-08-10 02:49 UTC, ayano-kobayashi-lvgs commented on src/resources/views/errors/403.blade.php
> +                            <a href="{{ route('todos.index') }}">Todo一覧に戻る</a>
もとにいたページに戻るようにするか一覧に戻るか迷っています

2022-08-10 07:16 UTC, takuya-nakamatsu-lvgs commented on src/app/Http/Requests/UserRequest.php
> +                'required'
```suggestion
                'required',
```

2022-08-10 07:16 UTC, takulev commented on src/app/Enums/Role.php
> +    public static function getRoleValues()
返り値の型指定がされてない

2022-08-10 07:16 UTC, takulev commented on src/app/Enums/Role.php
> +    public static function isAdmin($role): bool
引数の型がない

2022-08-10 07:21 UTC, takulev commented on src/app/Enums/Role.php
> +     * 権限のDB値 全件取得
この項目自体はDBから取得した値ではないので、
「Role（権限）名を取得する全件する取得する関数」って良いんじゃない？

2022-08-15 23:46 UTC, takulev reviewed
ごめん、前のレビューでのコメント漏れです笑

2022-08-15 23:46 UTC, takulev commented on src/database/migrations/2022_08_08_072444_add_role_to_users_table.php
> +            $table->string('role');
【More】
Moreな内容だけど、下記の視点を踏まえると、別テーブルとしてroleを管理を管理するのも一つかなって思った
- テーブルの正規化
- もし本当の開発を想定して、権限を動的に作成可能にする

2022-08-16 02:49 UTC, ayano-kobayashi-lvgs commented on src/resources/views/errors/common.blade.php
> +                    </p>
エラー画面の共通化を行いました。
エラーステータスコードによって、表示が変わるようになっています。

2022-08-16 07:37 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
レビューしました！

2022-08-16 07:37 UTC, takulev commented on src/app/Enums/Role.php
> +        return Role::toArray();
30行目に合わせて、`self`の方が良い気がした！
（それか30行目を`Role`にするかで統一した方いいかな）

```suggestion
        return self::toArray();
```

2022-08-16 07:37 UTC, takulev commented on src/app/Exceptions/Handler.php
> +            $e = new HttpException(500, $e->getMessage(), $e);
`500`はマジックナンバーだから、下記の定数で表現すると良いかも！
```suggestion
use Illuminate\Http\Response; // ファイル上部のuse側で定義

            $e = new HttpException(Response::HTTP_INTERNAL_SERVER_ERROR, $e->getMessage(), $e);
```
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpFoundation/Response.php#L24-L86

2022-08-16 07:37 UTC, takulev commented on src/app/Exceptions/Handler.php
> +    protected function renderHttpException(HttpExceptionInterface $e): Response
いいね！

2022-08-16 07:37 UTC, takulev commented on src/app/Policies/TodoPolicy.php
> +    }
このあたりってbooleanをreturnするんじゃなくて、voidで良いんだっけ？

公式見てる感じだと、returnしている笑
https://readouble.com/laravel/8.x/ja/authorization.html

2022-08-16 07:37 UTC, takulev commented on src/resources/views/errors/illustrated-layout.blade.php
> +<!DOCTYPE html>
このファイルって使ってるのー？？

2022-08-16 07:37 UTC, takulev commented on src/resources/views/errors/minimal.blade.php
> +<!DOCTYPE html>
同じくこのファイルも使ってる？？

2022-08-16 07:50 UTC, jaegon-kim-lvgs requested changes

2022-08-16 07:50 UTC, jaegon-kim-lvgs commented on src/.gitignore
> +gi
必要なければ削除

2022-08-16 08:01 UTC, ayano-kobayashi-lvgs commented on src/app/Policies/TodoPolicy.php
> +    }
そのとおりです！

2022-08-16 09:46 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
コメントしました！ラスト！がんばって！

2022-08-16 09:46 UTC, takulev commented on src/app/Policies/TodoPolicy.php
> +    }
このあたりの関数に`return`がないかな！

2022-08-16 23:51 UTC, ayano-kobayashi-lvgs commented on src/app/Policies/TodoPolicy.php
> +    }
すみません、直しました。。。

2022-08-16 23:57 UTC, takulev approved these changes
![95d3a71e](https://user-images.githubusercontent.com/50987589/185004976-a3ab75bd-28cf-410a-b30c-c92807796187.jpeg)

2022-08-17 00:01 UTC, merged