多言語対応
ayano-kobayashi-lvgs/laravel_todo_default pull request #7
Opened 2022-08-24 09:49 UTC by ayano-kobayashi-lvgs

2022-08-24 10:56 UTC, takulev reviewed
@ayano-kobayashi-lvgs 
コメントしました！

2022-08-24 10:56 UTC, takulev commented on src/app/Http/Controllers/Auth/LogoutController.php
> +        $lang = session('locale');
変数定義する必要なさそう！

2022-08-24 10:56 UTC, takulev commented on src/app/Http/Controllers/TodoController.php
> +        $message = __('todo.updated');
これも変数定義する必要ないかな〜

2022-08-24 10:56 UTC, takulev commented on src/app/Http/Middleware/Language.php
> +        if (!in_array($locale, ['ja', 'en'])) {
`ja`, `en`はEnumで管理しても良さそう！

2022-08-24 10:56 UTC, takulev commented on src/app/Http/Middleware/Language.php
> +    private function setLocale(string $locale): void
関数化するメリットをあんまり感じない笑

2022-08-24 10:56 UTC, takulev commented on src/resources/lang/ja/errors.php
> +
```suggestion
```

2022-08-24 10:56 UTC, takulev commented on src/app/Http/Requests/BaseRequest.php
> -        '*.unique' => '既に登録されています。',
多言語化のベストプラクティスを把握してないから、確実なことを言えないけど、これは消してはいけない気がしたり笑

この日本語の部分を`__()`にしたほうが良い気がする。
そうしないと、エラー項目に対しての表示するメッセージを把握する時に、わざわざviewファイルを見にいかないといけなさそう。

2022-08-24 10:56 UTC, takulev commented on src/resources/lang/en/errors.php
> +
```suggestion
```

2022-08-24 10:56 UTC, takulev commented on src/resources/lang/en/errors.php
> +
粒度が違うという理由で改行しているなら、そもそも定義する粒度が異なることがマズイかな〜

2022-08-24 10:56 UTC, takulev commented on src/resources/lang/ja/validation.php
> +<?php
Requests配下の定義をここに持ってきたのか！なるほど〜
Requestの部分でもコメントした理由で、Requests配下に定義してください！

2022-08-24 10:56 UTC, takulev commented on src/resources/views/auth/login.blade.php
> +                {{ config('languages.ja') }}
configヘルパーは設定を参照することを目的としていて、表示を目的としてないから不適切だと思った！

2022-08-24 10:56 UTC, takulev commented on src/routes/web.php
> +Route::group(['prefix' => '{lang?}', 'middleware' => 'lang'], function () {
【尚可】
langに入る文字列を正規表現にしても良いかも！

2022-08-25 01:15 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $message = __('todo.updated');
要確認

2022-08-25 01:15 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/LogoutController.php
> +        $lang = session('locale');
要確認

2022-08-25 01:19 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Middleware/Language.php
> +    private function setLocale(string $locale): void
修正済み

2022-08-25 01:20 UTC, ayano-kobayashi-lvgs commented on src/resources/lang/ja/errors.php
> +
修正済み

2022-08-25 01:21 UTC, ayano-kobayashi-lvgs commented on src/resources/lang/en/errors.php
> +
特に意味はないです

2022-08-25 01:36 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/login.blade.php
> +                {{ config('languages.ja') }}
修正済み

2022-08-25 05:14 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/Auth/LogoutController.php
> +        $lang = session('locale');
修正済み

2022-08-25 05:16 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Controllers/TodoController.php
> +        $message = __('todo.updated');
修正済み

2022-08-25 05:46 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/BaseRequest.php
> -        '*.unique' => '既に登録されています。',
要相談

2022-08-25 06:01 UTC, jaegon-kim-lvgs requested changes

2022-08-25 06:01 UTC, jaegon-kim-lvgs commented on src/resources/views/todo/index.blade.php
> +@section('title', __('todo.todo_list'))
TDKHに使う翻訳は本文に使うものとは「ページタイトル専用の文章が入ることが多い」、「本文の翻訳変更が反映されてしまう」ことから、分けたほうがいいと思います。

2022-08-25 06:01 UTC, jaegon-kim-lvgs commented on src/app/Http/Requests/BaseRequest.php
> -        '*.unique' => '既に登録されています。',
上記と同じ意見です。
Requestの中で翻訳関数を使うか、翻訳キーをruleキーと同じく揃えるかですかね

2022-08-25 06:25 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Middleware/Language.php
> +        if (!in_array($locale, ['ja', 'en'])) {
修正済み

2022-08-25 06:26 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Requests/BaseRequest.php
> -        '*.unique' => '既に登録されています。',
validatoin.phpに全移動。

2022-08-25 06:28 UTC, ayano-kobayashi-lvgs commented on src/resources/views/todo/index.blade.php
> +@section('title', __('todo.todo_list'))
今回はTDKH定義していないです！
今後同じことを行うとき、意識します。ありがとうございます。

2022-08-25 06:36 UTC, ayano-kobayashi-lvgs commented on src/resources/lang/ja/validation.php
> +<?php
validatoin.phpに全移動。

2022-08-25 06:58 UTC, jaegon-kim-lvgs requested changes

2022-08-25 06:58 UTC, jaegon-kim-lvgs commented on src/resources/lang/ja/validation.php
> +            'regex' => '英大文字・小文字・数字の組み合わせ(8~24桁)で入力してください。',
8と24（minとmax）はruleで定義してパラメーターとして翻訳に渡すようにしてください

2022-08-25 06:58 UTC, jaegon-kim-lvgs commented on src/resources/views/auth/login.blade.php
> +                {{ config('languages.en') }}
config('languages')のforeachで実装できそう

2022-08-25 06:58 UTC, jaegon-kim-lvgs commented on src/app/Http/Middleware/Language.php
> +        if (!in_array($locale, ['ja', 'en'])) {
せっかくconfigのlanguageを定義したので活用してください

2022-08-25 06:58 UTC, jaegon-kim-lvgs commented on src/app/Http/Middleware/Language.php
> +            $fallback = session('locale') ?: config('app.fallbacklocale');
config('app.fallbacklocale') -> config('app.fallback_locale')

2022-08-25 07:00 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Middleware/Language.php
> +            $fallback = session('locale') ?: config('app.fallbacklocale');
修正済み

2022-08-25 23:51 UTC, ayano-kobayashi-lvgs commented on src/resources/views/auth/login.blade.php
> +                {{ config('languages.en') }}
https://github.com/ayano-kobayashi-lvgs/laravel_todo_default/pull/7#discussion_r953646998
> configヘルパーは設定を参照することを目的としていて、表示を目的としてないから不適切だと思った！

修正済みです。
configは表示用でないそうなので、Enumを使いました。

2022-08-25 23:53 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Middleware/Language.php
> +            $fallback = session('locale') ?: config('app.fallbacklocale');
https://github.com/ayano-kobayashi-lvgs/laravel_todo_default/pull/7#discussion_r953637510
> `ja`, `en`はEnumで管理しても良さそう！

どちらで実装するか、要検討。

2022-08-26 00:29 UTC, ayano-kobayashi-lvgs commented on src/app/Http/Middleware/Language.php
> +            $fallback = session('locale') ?: config('app.fallbacklocale');
当初は、configを使って、選択欄やミドルウェアで値を取得しようと思っていましたが、表示用にEnumを作ったため、configを消してすべてEnumで管理するようにしました。

2023-01-17 06:02 UTC, merged